In [1]:
#Practising numpy functions 

In [2]:
import numpy as np


# 1. Create a NumPy array using np.array()
arr = np.array([1, 2, 3, 4, 5])
print("np.array ->", arr)

np.array -> [1 2 3 4 5]


In [3]:
# 2. Create an Identity Matrix using np.eye()
eye_matrix = np.eye(4)  # 4x4 identity matrix
print("\nnp.eye ->\n", eye_matrix)


np.eye ->
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
# 3. Create evenly spaced numbers using np.linspace()
lin_space = np.linspace(0, 10, 5)  # 5 numbers between 0 and 10
print("\nnp.linspace ->", lin_space)


np.linspace -> [ 0.   2.5  5.   7.5 10. ]


In [5]:
# 4. Create a range of numbers using np.arange()
arange_arr = np.arange(0, 10, 2)  # from 0 to 10 with step 2
print("\nnp.arange ->", arange_arr)


np.arange -> [0 2 4 6 8]


In [6]:
# 5. Create an array of zeros using np.zeros()
zeros_arr = np.zeros((3, 4))  # 3x4 matrix filled with 0
print("\nnp.zeros ->\n", zeros_arr)


np.zeros ->
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# 6. Create an array of ones using np.ones()
ones_arr = np.ones((2, 5))  # 2x5 matrix filled with 1
print("\nnp.ones ->\n", ones_arr)


np.ones ->
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
# 7. Create an array filled with a constant value using np.full()
full_arr = np.full((3, 3), 7)  # 3x3 matrix filled with 7
print("\nnp.full ->\n", full_arr)


np.full ->
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [9]:
# 8. Random numbers using np.random.rand()
rand_arr = np.random.rand(2, 3)  # 2x3 array with random floats [0,1)
print("\nnp.random.rand ->\n", rand_arr)



np.random.rand ->
 [[0.9829506  0.04920166 0.74349517]
 [0.64933699 0.6280579  0.8577984 ]]


In [10]:
# 9. Random integers using np.random.randint()
rand_int = np.random.randint(1, 100, size=(3, 3))  # 3x3 random integers between 1 and 100
print("\nnp.random.randint ->\n", rand_int)


np.random.randint ->
 [[66 38 82]
 [59 27 71]
 [83 84 87]]


In [11]:
# 10. Create indices grid using np.indices()
ind = np.indices((3, 3))  # returns grid indices
print("\nnp.indices ->\n", ind)


np.indices ->
 [[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [12]:
# 11. Check array attributes (ndim, size, shape)
print("\nArray Attributes:")
print("ndim (number of dimensions):", arr.ndim)
print("size (total number of elements):", arr.size)
print("shape (rows, columns):", arr.shape)



Array Attributes:
ndim (number of dimensions): 1
size (total number of elements): 5
shape (rows, columns): (5,)


In [13]:
# 12. Reshape an array using np.reshape()
reshaped = np.arange(12).reshape(3, 4)  # 12 elements reshaped into 3x4
print("\nnp.reshape ->\n", reshaped)


np.reshape ->
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
# 13. Transpose of a matrix using np.transpose()
transposed = reshaped.T
print("\nnp.transpose ->\n", transposed)


np.transpose ->
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [15]:
# 14. Mathematical operations
math_arr = np.array([1, 2, 3, 4, 5])
print("\nSum:", np.sum(math_arr))
print("Mean:", np.mean(math_arr))
print("Max:", np.max(math_arr))
print("Min:", np.min(math_arr))
print("Standard Deviation:", np.std(math_arr))


Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951


In [16]:
# 15. Create diagonal matrix using np.diag()
diag_arr = np.diag([10, 20, 30])
print("\nnp.diag ->\n", diag_arr)


np.diag ->
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [17]:
# 16. Flatten array using np.ravel()
flat = reshaped.ravel()
print("\nnp.ravel (flatten) ->", flat)


np.ravel (flatten) -> [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
# 17. Sorting array using np.sort()
unsorted = np.array([3, 1, 5, 2, 4])
sorted_arr = np.sort(unsorted)
print("\nnp.sort ->", sorted_arr)


np.sort -> [1 2 3 4 5]


In [19]:
# 18. Unique values using np.unique()
dup_arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_vals = np.unique(dup_arr)
print("\nnp.unique ->", unique_vals)


np.unique -> [1 2 3 4 5]
